stages:
  - build
  - deploy

variables:
  CHART_NAME: tabookey-relay-server
  ECR_REPO: 959807571188.dkr.ecr.eu-west-1.amazonaws.com/tabookey-relay-server


build_docker_image:
  stage: build
  script:
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t ${CHART_NAME} .
    - docker tag ${CHART_NAME}:latest ${ECR_REPO}:develop
    - docker push ${ECR_REPO}:develop
  when: manual
  only:
    - develop


helm_deploy:
  stage: deploy
  script:
    - aws --profile cc-dev eks update-kubeconfig --name cc-dev-eks --region eu-west-1
    - helm init --service-account tiller --tiller-namespace dev --client-only
    - helm repo add cc-charts http://gitlab.closecross.com:8081
    - helm repo update
    - helm upgrade --install
      --tiller-namespace dev
      --namespace dev
      --set image.tag=develop
      --set ingress.hosts[0].host=gaslessrelay.dev.closecross.com
      --set ingress.hosts[0].paths[0]=""
      tabookey-relay-server cc-charts/tabookey-relay-server
  when: manual
  only:
    - develop
  